# -*- coding: utf-8 -*-
"""Copy of AFM244_S26_Week11_Quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pblP3v1cEs-cRiMId3NRVynYLddgCgV
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
# sklearn aka scikitlearn
import matplotlib.pyplot as plt

pd.options.display.float_format = '{:.2f}'.format

qSales = pd.read_csv('qSales_2024.csv')

display(qSales)

apple_sales = qSales.loc[qSales['tic']=='AAPL']

display(apple_sales)

#Step 0 - make sure the date is recognized as a date - important during regression especially
# time series regression
apple_sales = qSales.loc[qSales['tic']=='AAPL']

#step 1 - always visualize the data

plt.figure(figsize=(10,6))

plt.title('apple revenues')

plt.xlabel('time')
plt.ylabel('revenue')

plt.plot(apple_sales['datadate'],apple_sales['saleq'], marker='o')

"""#time series forecasting is just using time as an independent variable to calculate our dependent variable"""

#step 1 is to incorporate a new "time" column, which will measure time periods
# similar to how in accounting and fiance you use Time 1, time 2, etc.
# we want our time column to have the time period number, so 1, 2, 3, etc. etc

apple_sales['time'] = range(1, len(apple_sales) + 1)

apple_sales

# this snippet of code splits datasets into 75% and 25%

dt4training = apple_sales[:int(0.75 * len(apple_sales))]

#this command will take everything AFTER the first 75% of rows - take colon to the end
dt4testing = apple_sales[int(0.75 * len(apple_sales)):]

display(dt4training)
display(dt4testing)

#first prepare the independent variable in our case thats just time
# second, prepare the dependent variable - revenue
# fit the model
# forecast values for our testing set

x = dt4training.loc[:,'time']
x = sm.add_constant(x)

y = dt4training.loc[:,'saleq']

model1 = sm.OLS(y,x).fit()

model1.params

"""# apple revenue = -13,536 + 1,077 * time"""

x_test = dt4testing.loc[:,'time']
x_test = sm.add_constant(x_test)

model1.predict(x_test)

# how to make python give you a range of predicted values rather than a specific one
# following code to get a range of predictions
# 1 - alpha = confidence level

model1.get_prediction(x_test).summary_frame(alpha=0.2) # confidence level of 80%
#model1.get_prediction(x_test).summary_frame(alpha=0.1) # confidence level of 90%

#pay attention to the OBS_ci_lower and upper figures and the mean, NOT MEAN_SE

apple_sales['release_dummy_variable'] = np.where(apple_sales['fqtr']==1,1,0)
apple_sales['release_dummy_interaction'] = apple_sales['time'] * apple_sales['release_dummy_variable']
display(apple_sales)

# ['2022-12-31','2021-12-31']

dt4training = apple_sales[:int(0.75 * len(apple_sales))]

#this command will take everything AFTER the first 75% of rows - take colon to the end
dt4testing = apple_sales[int(0.75 * len(apple_sales)):]

dt4training

x = dt4training.loc[:,['time', 'release_dummy_variable','release_dummy_interaction']]
x = sm.add_constant(x)

y = dt4training.loc[:,'saleq']

model1 = sm.OLS(y,x).fit()

model1.params

"""# apple revenue = -11,044 + 933 * time + (-10,422) * release_dummy_variable + 578 * release_dummy_interaction

release_dummy_interaction = time * dummy variable
"""

x_test = dt4testing.loc[:,['time','release_dummy_variable','release_dummy_interaction']]
x_test = sm.add_constant(x_test)

model1.get_prediction(x_test).summary_frame(alpha=0.2)

dt4testing

"""#To forecast actual future values outside the dataset
Step 1: create synthetic future datasets for your time periods, dummy variables, and interaction terms

Step 2: do the exact same steps as testing your model, except use the synthetic data instead of the testing data
"""

synth_data = pd.read_csv('synthetic_data.csv')
display(synth_data)

x_test = synth_data.loc[:,['time','release_dummy_variable','release_dummy_interaction']]
x_test = sm.add_constant(x_test)

model1.get_prediction(x_test).summary_frame(alpha=0.2)

"""# Week 11 Quiz"""

qSales = pd.read_csv('qSales_2024.csv')
sales = qSales.loc[qSales['tic']=='TGT']
display(sales)

plt.figure(figsize=(10,6))
plt.title('Company revenues')
plt.xlabel('time')
plt.ylabel('revenue')
plt.plot(sales['datadate'],sales['saleq'], marker='o')
plt.show()

sales['time'] = range(1, len(sales) + 1)

# splits datasets into 75% and 25
dt4training = sales[:int(0.75 * len(sales))]
dt4testing = sales[int(0.75 * len(sales)):]
# training
x = dt4training.loc[:,'time']
x = sm.add_constant(x)
y = dt4training.loc[:,'saleq']
model1 = sm.OLS(y,x).fit()
model1.params

# testing
x_test = dt4testing.loc[:,'time']
x_test = sm.add_constant(x_test)
model1.predict(x_test)

# how to make python give you a range of predicted values rather than a specific one
# following code to get a range of predictions
# 1 - alpha = confidence level
model1.get_prediction(x_test).summary_frame(alpha=0.2) # confidence level of 80%
#model1.get_prediction(x_test).summary_frame(alpha=0.1) # confidence level of 90%
#pay attention to the OBS_ci_lower and upper figures and the mean, NOT MEAN_SE

sales['release_dummy_variable'] = np.where(sales['fqtr']==4,1,0)
sales['release_dummy_interaction'] = sales['time'] * sales['release_dummy_variable']
display(sales)

# creating new training with release dummy variable and dummy interaction
dt4training = sales[:int(0.75 * len(sales))]
dt4testing = sales[int(0.75 * len(sales)):]
# training
x = dt4training.loc[:,['time', 'release_dummy_variable','release_dummy_interaction']]
x = sm.add_constant(x)
y = dt4training.loc[:,'saleq']
model1 = sm.OLS(y,x).fit()
model1.params

# testing
x_test = dt4testing.loc[:,['time','release_dummy_variable','release_dummy_interaction']]
x_test = sm.add_constant(x_test)
model1.get_prediction(x_test).summary_frame(alpha=0.2)

plt.figure(figsize=(10,6))
plt.title('revenue forecast with dummy variable using testing data')
plt.xlabel('time')
plt.ylabel('revenue')
plt.plot(dt4testing['time'],dt4testing['saleq'], marker='o')
plt.plot(dt4testing['time'],model1.predict(x_test), marker='o')
plt.show()

x_test = dt4testing.loc[:,['time','release_dummy_variable','release_dummy_interaction']]
x_test = sm.add_constant(x_test)
dt4testing['rev_predicted'] = model1.predict(x_test)
dt4testing['abs_pct_error'] = abs((dt4testing['rev_predicted']
                                     - dt4testing['saleq'])/dt4testing['saleq'])
print("MAPE = ", dt4testing['abs_pct_error'].mean()) # MAPE

"""To: Chapman Wealth Management

From: Equity Research Analyst at Quantfolio Solutions
4
Date: July 2th, 2026

Re: Forecasting model for predicting Target revenue from data

Bottom line. The Target revenue forecast using sales data and a 4th quarter dummy variable provided a better predictive model.

Scope. Made use of a provided representative data set and used it to train a time forecasting regression models based on 4th quarter sales data. This data was used to predict revenue. Performance of the predictive models was tested with testing data and visualized.

Methodology. The data set was split into 75% training and 25% testing data. The model was trained using dummy variables marking the 4th quarter sales numbers. Performance was evaluated for both using the Mean Average Percent Error (MAPE) and visualized on a graph of sales testing data.

Key Findings. The forecast model with dummy variables had a low MAPE score of 12.0%. Observing the 80% confidence intervals, the lower and upper bounds were relatively tight on the revenue predictions.

Recommendations. It is recommended that Chapman Wealth Management consider using a forecasting model with 4th quarter dummy variable, since it provides a more accurate prediction of Target actual revenue. Further modeling based on using other data variables should be investigated to see if a better predictive forecasting model is possible with a even lower MAPE score.

"""